name: CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '*publish')"
    strategy:
      matrix:
        node-version: ['16']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - run: |
          echo "${{secrets.DIGSHARE_REGISTRY}}" > ~/.npmrc
      - run: npm install --global yarn
      - run: yarn install
      - run: node publish
